// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "7a1f6b6b-4885-49a1-b47b-8f8d53324d44";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onTargetChange();

float curr_diff;
float max_diff_cycle;
float target;
float temp_outside;
bool compressor_state;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(curr_diff, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(max_diff_cycle, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(target, READWRITE, ON_CHANGE, onTargetChange);
  ArduinoCloud.addProperty(temp_outside, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(compressor_state, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
